name: kanban_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.10
  get_it: ^5.0.1
  flutter_bloc: ^6.1.1
  equatable: ^1.2.5
  dartz: ^0.9.2
  flutter_secure_storage: ^3.3.5
  boardview: ^0.1.2
  font_awesome_flutter: ^8.10.1
  shimmer: ^1.1.2
  modal_bottom_sheet: ^1.0.0+1
  cupertino_icons: ^1.0.1
  carousel_slider: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/



